export const listaPessoas = [
    {
        nome:"Carlos",
        idade:39
        },
    {
        nome:"Igor",
        idade:22
    },
    {
        nome:"Marcos",
        idade:19
    },
    {
        nome:"Carina",
        idade:29
    },
    {
        nome:"Marcela",
        idade:49
        },
    {
        nome:"Roberto",
        idade:23
    },
    {
        nome:"Julia",
        idade:21
    },
    {
        nome:"Guilherme",
        idade:42
    },
    {
        nome:"Mauricio",
        idade:39
    },
    {
        nome:"Ingrid",
        idade:22
    }
                   ]